#ifndef SOFTPROJECTOR_VERSION_HPP
#define SOFTPROJECTOR_VERSION_HPP

#define SOFTPROJECTOR_VERSION "2.3.0-beta.1"
#define SOFTPROJECTOR_VERSION_LABEL "2.3.0 Beta 1"
#define SOFTPROJECTOR_VERSION_WINDOWS 2,3,0,1

#endif // SOFTPROJECTOR_VERSION_HPP
